project:
  type: website
  render:
    - "index.qmd"
    - "subject/*.qmd"
website:
  title: "AIML4OS Funathon - Project 1"
  page-navigation: true
  description: "Predicting housing prices"
  site-url: "https://AIML4OS.github.io/funathon-project1/"
  repo-url: "https://github.com/AIML4OS/funathon-project1"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right:
    - text: "License"
      href: LICENCE

  navbar:
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: "https://github.com/AIML4OS/funathon-project1"
        aria-label: GitHub

    left:
      - text: "0. Introduction"
        menu: 
        - text: "Presentation"
          href: subject/introduction.qmd
        - text: "Data presentation"
          href: subject/intro_data.qmd
      - text: "1. Preprocessing"
        href: subject/1-preprocessing.qmd
      - text: "2. Modelling"
        menu:
        - text: "with a random forest"
          href: subject/2-RF_model.qmd
        - text: "with a gradient boosting"
          href: subject/2-GB_model.qmd
      - text: "3. Model evaluation"
        href: subject/3-metrics.qmd
      - text: "4. Model logging"
        href: subject/4-logging.qmd
      - text: "5. Deployment"
        href: subject/5-deployment.qmd


format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    reference-location: margin
    code-copy: true
    code-overflow: wrap
    grid:
      body-width: 1100px

execute: 
  eval: false
  cache: false
  warning: false
