---
title: "Detailed presentation of the data"
lang: en-US
format:
  html:
    number-sections: true
    grid: 
      body-width: 1100px

---

# Real estate transactions in France

## How to buy a property in France ?

A housing transaction is always formalized in front of a **notary** in France, who acts as a legal intermediary to ensure the transaction's validity and compliance with civil law. The notary checks among other things that the property effectively belongs to the seller, calculates and collects the **stamp duties** (such as *droits de mutation*) based on the transaction's details and the property's characteristics.

After collecting these taxes, the notary sends the details of the transaction to the **tax administration**, including the sale price, the identities of the buyer and seller, the property's cadastral reference and the notarized document. The fiscal administration then records this information in its databases and updates the **land registry** to reflect the new ownership.

## Specificity of the dataset

Since 2019, the fiscal administration releases **all real estate transactions** twice a year in open data format on data.gouv.fr. You can access and download the original datasets (*Demande de Valeurs Foncières - DVF* or request for property values) directly here (in French only - sadly 😞): [data.gouv.fr/datasets/demandes-de-valeurs-foncieres](https://www.data.gouv.fr/datasets/demandes-de-valeurs-foncieres).

**Types of transaction stored**:

What transactions are described in the DVF dataset is a complex question. It's key to remember that the first goal of the dataset is to collect taxes. As a consequence, the dataset does not contain transactions that are exempted from stamp duties. In addition, some transactions are registered in the data when they are of little interest to us. For example:

-   The DVF records _partial_ transactions, for example when a property is jointly owned by two people, and one of them buys back the share of the other. In this case, the recorded price is the price paid for the share, not the total value of the assets. Unfortunately, the DVF dataset does not specify what **share of ownership** is sold or whether the transaction is a partial one.
-   The initial transfer of ownership from an individual to an SCI is recorded as a housing transaction, even if the SCI is owned by the very same persons.

**Geographic coverage of the data** :

The dataset includes **overseas territories** such as Guadeloupe, Martinique, and Réunion, but excludes **Alsace-Moselle** (the eastern departments of Bas-Rhin, Haut-Rhin, and Moselle). This exclusion is due to the **local civil law** (*droit local*), which applies in Alsace-Moselle because these territories were part of Germany from 1870 to 1918. It is not an issue as we will focus on the Paris region but keep this in mind if you want to play around with the data.

**Geographical codes** :

The French territory is split in 101 administrative regions called _départements_. Each _département_ is identified with a unique non numeric **department code**, such as *75* for Paris or *2A* for southern Corsica.

The **official geographic code** — commonly referred to as the **Insee code** — is a unique five-digit identifier assigned by the National Institute of Statistics and Economic Studies ([Insee](https://www.insee.fr/en/metadonnees/source/serie/s2084)) to each city, department, region and other administrative area. This code allows to uniquely identify a city (or equivalent) and remains constant even if the city's name changes or if it merges with another municipality. The two first digits of the city's Insee code is the department code. You can find the full COG data and documentation here: [Insee - Code Officiel Géographique (COG)](https://www.insee.fr/fr/information/2560452) and in open data format here: [data.gouv.fr - Code Officiel Géographique (COG)](https://www.data.gouv.fr/datasets/code-officiel-geographique-cog).

In everyday life, the zip code is more frequent to Insee code. It means that if you search for a city with its Insee code on Google Maps for example, it won't find it as it uses the **zip code** (or postal code). The zip code is not a reliable identifier for a city as multiple cities share the same zip code, and a single city may have several zip codes depending on its districts or neighborhoods.

For example, the city of Paris is identified by the department code **75**, the Insee code **75056** (Paris itself), and is associated with multiple zip codes (e.g., **75001**, **75002**, etc.). Montrouge's Insee code is 92049 and 92 is the department code of Hauts-de-Seine, where Montrouge is located.


# General presentation of the data

Data prepared for this project gathers all of the housing transactions in France between 2014 and 2024 and details about the property sold.
Because the characteristics of the property sold isn't open source, the data you'll be working with is **synthetic data**. It has been generated to mirror the original data.

If you want to have a closer look at the data, CEREMA publishes on [its website](%5D(https://doc-datafoncier.cerema.fr/doc/ff/pb0010_local)) an extensive documentation of the different datasets, the variables, their modalities and the overall quality of variable.

# List of variables

|     | Label of the variable   | Full name of the variable      | Explanation and remarks       | Original label of the variable (French)   |
|--:|:---------|:---------------------------------|:------------------------------------------------------------------|:-------------|
|   1 | dist_tosea              | Distance of the property to the nearest seashore - capped at 10km                       | This variable has been calculated      | distance_ltm (calculated)                 |
|   2 | farea                   | Floor area of the property                         |                           | dsupdc        |
|   3 | has_cheating            | If the property has access to central heating               | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gchclc        |
|   4 | has_elec                | If the property has access to electricity                   | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gelelc        |
|   5 | has_elevator            | If the building of the flat has an elevator (for flats only)| The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gasclc        |
|   6 | has_gas                 | If the building is connected to the gas mains               | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | ggazlc        |
|   7 | has_mdrainage           | If the property is connected to the mains drainage system   | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gteglc        |
|   8 | has_rchute              | If the building of the flat has refuse chutes (for flats only)                          | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gvorlc        |
|   9 | has_water               | If the property has access to water                         | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | geaulc        |
|  10 | n_ancrooms              | Number of ancillary rooms reported in the property          | Ancillary rooms include hallways, attics. They differ from n_otherannex.                       | dnbann        |
|  11 | n_attic                 | Number of attics reported in the whole property             |                           | nb_greniers (calculated)                  |
|  12 | n_basmt                 | Number of basements reported in the whole property          |                           | nb_caves (calculated)                     |
|  13 | n_bath                  | Number of bathtubs reported in the property                 |                           | dnbbai        |
|  14 | n_eatr                  | Number of eating rooms reported in the property             |                           | dnbsam        |
|  15 | n_floors                | Number of floor in the property (building or house)         | This variable is more reliable with houses than with buildings. Underground floors encoding is not fully harmonized and is often equal to 81 for minus 1, 82 for minus 2 ... It can also be encoded as 99, 98. A flat at the 2nd floor of a seven-floors building should be encoded with nth_floor=1 and n_floors=8 (ground floor and seven floors above ground level)             | dnbniv        |
|  16 | n_garage                | Number of garages reported in the whole property            |                           | nb_garages (calculated)                   |
|  17 | n_kit8                  | Number of kitchens reported in the property with an area of less than 8 square meters   |                           | dnbcu8        |
|  18 | n_kit9                  | Number of kitchens reported in the property with an area of larger than 9 square meters |                           | dnbcu9        |
|  19 | n_mrooms                | Number of main rooms reported in the property               | n_mrooms = n_eatr + n_slr + n_kit8 + n_kit9 + n_washr              | dnbppr        |
|  20 | n_otherannex            | Number of other annexes reported in the whole property      |                           | nb_autresdep (calculated)                 |
|  21 | n_pool                  | Number of pools reported in the whole property              |                           | nb_piscines (calculated)                  |
|  22 | n_rooms                 | Number of rooms reported in the property                    | n_rooms = n_mrooms + n_annex           | dnbpdc        |
|  23 | n_show                  | Number of showers reported in the property                  |                           | dnbdou        |
|  24 | n_sink                  | Number of sinks reported in the property                    |                           | dnblav        |
|  25 | n_slr                   | Number of sleeping rooms reported in the property           |                           | dnbcha        |
|  26 | n_terrace               | Number of terraces reported in the whole property           |                           | nb_terrasses (calculated)                 |
|  27 | n_washr                 | Number of washing rooms reported in the property            |                           | dnbsea        |
|  28 | n_wc                    | Number of toilets reported in the property                  |                           | dnbwc         |
|  29 | nth_floor               | Reported floor of the property  | It represents the floor of the flat (in France, the second floor is the first floor above ground level). This variable is set to 00 for houses. Underground floors encoding is not fully harmonized and is often equal to 81 for minus 1, 82 for minus 2 ... It can also be encoded as 99, 98. A flat at the 2nd floor of a seven-floors building should be encoded with nth_floor=1 and n_floors=8 (ground floor and seven floors above ground level). | dniv          |
|  30 | price                   | Price of the transaction        | Price of the transaction is in EUR     | valeurfonc    |
|  31 | price_sqm               | Price per square meter of the transaction                   |                           | price_sqm (calculated)                    |
|  32 | prop_loc_citycode       | Official city's code where the property is located          | see remarks above         | depcom        |
|  33 | prop_loc_dep            | Department code where the property is located               | Data doesn't cover the whole French territory - overseas territory are included but Alsace-Moselle (Eastern part of France) isn't       | ccodep        |
|  34 | prop_loc_x              | Longitude where the property is located                     | see remarks above         | x             |
|  35 | prop_loc_y              | Latitude where the property is located                      | see remarks above         | y             |
|  36 | prop_type               | Type of property   | 1 represents a flat and 2 a house      | dteloc        |
|  37 | prop_year_harm          | Year of contruction of the property                         | This variable has been harmonized to correct for typing mistakes. More details is available in the introduction.                        | jannath       |
|  38 | s_land_agri             | Agricultural land area (square meters)                      | Agricultural land is used for farming. It includes fields, meadows, orchards and vineyards.    | dcntagri      |
|  39 | s_land_artif            | Artificial land area (square meters)                        | Artificial land includes recreational areas, land, building plots and gardens. Artificial land refers to land that has been altered by humans.                      | dcntsol       |
|  40 | s_land_nat              | Natural land area (square meters)                           | Natural land is land that has not been altered. This includes, for example, forests.           | dcntnat       |
|  41 | stair                   | If the building of the flat has stairs (for flats only)     | The modalities are coded in the following way : <br> - `0` : `No` <br> - `1` : `Missing value` <br> - `2` : `Yes`                       | gesclc        |
|  42 | trans_date              | Date of the official certified transaction                  |                           | datemut       |
|  43 | trans_month             | Month of the official certified transaction                 |                           | moismut       |
|  44 | trans_year              | Year of the official certified transaction                  |                           | anneemut      |

See [CEREMA's documentation (in French)](https://doc-datafoncier.cerema.fr/doc/ff/pb0010_local) for a more detailled description.

# Detailed note 

Note that the variable year of the building has been harmonized to correct for typing mistakes. Here are the transformation made from the original data :

| Original modality | Corrections to original modality | Exemple of transformation |
|------------------------|------------------------|------------------------|
| 1 ≤ prop_year ≤ 22 | Add 2000 as the first digits were not entered | 8 → 2008 |
| 23 ≤ prop_year ≤ 99 | Add 1900 as the first digits were not entered | 83 → 1983 |
| 100 ≤ prop_year ≤ 119 | Set to 0 as it is unknown | 105 → 0 |
| 120 ≤ prop_year ≤ 200 | Add a 0 at the end as the last digit has not been entered | 187 → 1870 |
| 201 ≤ prop_year ≤ 299 | Set to 0 as it is unknown | 250 → 0 |
| 300 ≤ prop_year ≤ 999 | Add 1000 as the first digits have not been entered | 980 → 1980 |
| 1000 ≤ prop_year ≤ 1120 | Set to 0 as it is unknown | 1005 → 0 |
| 1120 ≤ prop_year ≤ 1199 | Replace the second 1 with 9 | 1155 → 1955 |
| 1200 ≤ prop_year ≤ 2022 | No change | 1200 → 1200 |

More information about this transformation is available [online](https://doc-datafoncier.cerema.fr/doc/ff/pb40_pevprincipale/prop_year_harm) (in French).

# Next step
Now that you've discovered the data, we can start having a deeper look at it and pre-processing it for our model. 

**Go to the [pre-processing section](2-preprocessing.qmd).**